SA-1152 [라미엘] ws-scrcpy에 git hash 표시
HardBoiledSmith/ws-scrcpy pull request #114
Opened 2022-10-28 05:02 UTC by ricepower

### What is this PR for?
- ws-scrcpy 하단에 git hash 표시

### How should this be tested?
- ws-scrcpy 실행 시 하단에 git hash 가 나타나야 함

### Screenshots
![스크린샷 2022-10-28 오후 1 55 06](https://user-images.githubusercontent.com/6683184/198506595-f300856c-9134-4d98-b8ed-4c41237ca278.png)

2022-11-03 02:25 UTC, singetta approved these changes
git hash 값 표시 추가 감사합니다. 처음 라미엘 관련 작업 하셨을 텐데 고생하였습니다. 기능 및 코드 상 크게 이견 없습니다.

2022-11-03 06:25 UTC, GoldieKMG approved these changes
![image](https://user-images.githubusercontent.com/42234701/199658833-e4f05934-a306-4ca7-ad24-7c5b36033a9b.png)
로직 추가 감사합니다 고생하셨습니다 🙏  PR 리뷰란에 개발하시면서 어떻게 테스트 진행 하셨는지 같이 작성해주시면 리뷰 진행 시 도움이 될 것 같습니다 :) 

저의 경우는 해당 PR 테스트 해보기 위해 M1 맥북에서 
BRANCH_WS_SCRCPY=SA-1152 ./provisioning.py on-premise 를 실행하여 테스트 진행했습니다.

2022-11-03 06:37 UTC, metocks requested changes
@ricepower // 리뷰 3건 검토 부탁드립니다 🙏

2022-11-03 06:37 UTC, metocks commented on src/server/goog-device/mw/WebsocketProxyOverAdb.ts
> +
@ricepower // 코드의 복잡도 감소를 위해, 함수로 분리하지 않는 것이 어떨까요? 🙏

2022-11-03 06:37 UTC, metocks commented on src/server/Utils.ts
> +            return {};
@ricepower // 이 경우 `undefined`가 우하단에 노출될 것으로 보입니다. 명시적으로 버전을 가져오지 못했다고 보여주는 것이 어떨지 검토 부탁드립니다 🙏

2022-11-03 06:37 UTC, metocks commented on package-lock.json
>          "@devicefarmer/adbkit": "^2.11.3",
@ricepower // package-lock.json은 커밋하지 않는 것을 권고하여 드립니다 🙏

2022-11-04 02:51 UTC, ricepower commented on package-lock.json
>          "@devicefarmer/adbkit": "^2.11.3",
@metocks // 제거했습니다. 🙏

2022-11-04 02:53 UTC, ricepower commented on src/server/Utils.ts
> +            return {};
@metocks // 예외발생시 에러 메세지를 추가했습니다. 🙏

2022-11-04 03:08 UTC, ricepower commented on src/server/goog-device/mw/WebsocketProxyOverAdb.ts
> +
@metocks 
`const service = new WebsocketProxyOverAdb(ws, udid);`
상단에 선언된 service 에서 함수를 호출하기 때문에 부득이하게 분리했습니다. 🙏

2022-11-06 05:58 UTC, metocks approved these changes
@ricepower // 리뷰 반영 감사합니다 👍 
추가로, 리뷰 반영 후 리뷰어 옆에 갱신 버튼을 눌러주시면 변경 요청자에게 알람을 보낼 수 있으니 참고 부탁드립니다 🙏 

![image](https://user-images.githubusercontent.com/12525941/200156596-e219c4e8-5a17-42e3-ad56-d0ea36f81d17.png)

2022-11-07 06:26 UTC, yoonjs2 commented
@metocks // 시헌님, 현재 ws-scrcpy 는 git으로 배포되는게 아닌 압축된 아티팩트 형태로 배포되고 있지 않나요? 개발 환경에서만 git hash가 동작하고 qa, op 환경에서는 이 기능이 동작하지 않을것 같은데 제가 이해하는게 맞을까요?

2022-11-07 06:44 UTC, metocks commented
> @metocks // 시헌님, 현재 ws-scrcpy 는 git으로 배포되는게 아닌 압축된 아티팩트 형태로 배포되고 있지 않나요? 개발 환경에서만 git hash가 동작하고 qa, op 환경에서는 이 기능이 동작하지 않을것 같은데 제가 이해하는게 맞을까요?

아니오. ws-scrcpy는 git으로 배포합니다.

2022-11-07 06:57 UTC, yoonjs2 requested changes
@ricepower // 아래 요구사항 반영 부탁드립니다.
- git hash 뿐만 아니라, branch 정보도 같이 나오도록 부탁드립니다. (아래예시 참고)
```
<브랜치>-<git hash>
op-aadvs12344dfsf2121
```
- Conflict 해결 부탁드립니다.

2022-11-08 01:20 UTC, yoonjs2 approved these changes

2022-11-08 01:20 UTC, merged