DEV-14886 [라미엘] sentry.io 연동
HardBoiledSmith/ws-scrcpy pull request #116
Opened 2022-11-02 09:13 UTC by metocks

### What is this PR for?

- sentry.io 연동

### How should this be tested?

- 배포 `BRANCH_WS_SCRCPY=DEV-14886 ./provisioning.py on-premise`
- 임의의 폰 연결
- 연결 끊어짐, 사용 중 장비 등의 사례 재현
- 브라우저 sentry.io --> Releases --> sample_ramiel 중 가장 최근 --> 메시지 확인
    - https://sentry.io/organizations/hbsmith-inc/releases/?project=4504053395292160
- Discovery --> Saved Queries --> sampleRamielEvents

### Screenshots (if appropriate)

- Issues
![image](https://user-images.githubusercontent.com/12525941/199450278-cf28f3ef-747e-40d3-87d8-8ccc96a171f1.png)

- discovery
![image](https://user-images.githubusercontent.com/12525941/199450514-a4e1966b-4b7d-4b98-8634-711403a7a569.png)

2022-11-03 04:11 UTC, yoonjs2 requested changes
@metocks // sentry 추가 감사합니다. 좀더 에러 핸들링를 깔끔하게 다듬을수 있을것 같아 제안드립니다.

2022-11-03 04:11 UTC, yoonjs2 commented on src/server/goog-device/mw/WebsocketProxyOverAdb.ts
> +                }
@metocks // iOS쪽과 동일하게 수정해 보았습니다.
```suggestion
               const self = this;
               Sentry.captureException(e, scope => {
                   scope.setTags('ramiel_device_type', 'Android');
                   scope.setTags('ramiel_device_id', self.udid);
                   scope.setTags('ramiel_message', e.ramiel_message);
                   return scope;
               });
```

2022-11-03 04:11 UTC, yoonjs2 commented on src/server/goog-device/mw/WebsocketProxyOverAdb.ts
> +            Utils.captureMessage(e.message, 'Android', this.udid);
@metocks // iOS쪽과 동일하게 수정해 보았습니다.
```suggestion
            const self = this;
            Sentry.captureException(e, scope => {
                 scope.setTags('ramiel_device_type', 'Android');
                 scope.setTags('ramiel_device_id', self.udid);
                 scope.setTags('ramiel_message', e.ramiel_message);
                 return scope;
            });
```

2022-11-03 04:11 UTC, yoonjs2 commented on src/server/goog-device/mw/WebsocketProxyOverAdb.ts
> +                Utils.captureMessage('Failed to run setUpTest', 'Android', this.udid);
@metocks // iOS쪽과 동일하게 수정해 보았습니다.
```suggestion
            const self = this;
            Sentry.captureException(e, scope => {
                 scope.setTags('ramiel_device_type', 'Android');
                 scope.setTags('ramiel_device_id', self.udid);
                 scope.setTags('ramiel_message', e.ramiel_message);
                 return scope;
            });
```

2022-11-03 05:31 UTC, singetta requested changes
@metocks // sentry.io 연동 관련 작업 고생하셨습니다. 아래 궁금한 사항이 있는데요. 확인 부탁드립니다.

2022-11-03 05:31 UTC, singetta commented on _provisioning/configuration/etc/ramiel/ws-scrcpy/settings_local.json
> +  "sentryProject": "sample-ramiel"
settings_local.json은 개인별 설정으로 알고 있는데요. 라미엘에서는 해당 파일을 github에 push하는걸까요?
그리고 sentryDSN 명을 추가해도 되는지 궁금합니다.
또한 sentryProject는 sample-ramiel인데 해당 값은 향후 magi에서 수정되는걸까요?

2022-11-03 05:41 UTC, yoonjs2 commented on _provisioning/configuration/etc/ramiel/ws-scrcpy/settings_local.json
> +  "sentryProject": "sample-ramiel"
@singetta // sentryDSN 명을 코드에 박는건 naoko, gendo의 사례를 참고해서 그렇습니다. DV/QA용 sentry DSN 값을 따로 만들지 않고 있기도 하고, OP 브랜치에서만 Sentry가 활성화 되도록 로직으로 강제하면 될것 같아 제가 @metocks 님께 부탁드렸습니다.
https://github.com/HardBoiledSmith/naoko/blob/4ea3c85cefc86b10a466085d8621721d3e114ed8/naoko/Program.cs#L21-L31
@metocks // sentryProject 이름은 실제 사용할 프로젝트 이름으로 대체되는게 좋을것 같습니다. 확인 부탁드립니다.

2022-11-03 05:57 UTC, singetta commented on _provisioning/configuration/etc/ramiel/ws-scrcpy/settings_local.json
> +  "sentryProject": "sample-ramiel"
@yoonjs2 // naoko, gendo 참고하여 그렇게 된거군요. hbsmith-web은 DSN값이 없어서 문의 드렸습니다. 답변 감사합니다.

2022-11-04 03:06 UTC, metocks commented
@yoonjs2 // 가능한 captureException을 사용하는 방안을 생각해보겠습니다.
다만 setContext는 설정 시 다른 메시지 전송에도 상시 적용되게 되어 사용할 수 없으니 참고 부탁드립니다:
참조) 사용 중 장비 에러에서 설정된 context가 연결 끊어짐에 영향을 미친 사례
<img width="880" alt="image" src="https://user-images.githubusercontent.com/12525941/199876298-25efb7bb-f35d-4fdb-8ca0-0a86972dcabd.png">

2022-11-04 03:10 UTC, yoonjs2 commented
> 

@metocks // 아래처럼 전송전에 clear 시키거나 따로 context 객체를 만들어서 전달하는 식으로 구현하면 어떨까요? 한번더 고려 부탁드립니다.
https://docs.sentry.io/platforms/javascript/enriching-events/context/#passing-context-directly
```
Sentry.captureException(new Error("clean as never"), scope => {
  scope.clear();
  scope.setTag("clean", "slate");
  return scope;
});
```
```
const scope = new Sentry.Scope();
scope.setTag("section", "articles");
Sentry.captureException(new Error("something went wrong"), scope);
```

2022-11-04 05:54 UTC, metocks commented
> > 
> 
> @metocks // 아래처럼 context 객체를 만들어서 Exception 객체에 붙여서 전달하는 식으로 구현하면 어떨까요? 한번더 고려 부탁드립니다. `Sentry.setContext()`는 global context를 수정하는거라 말씀하신 문제가 있긴 합니다. https://docs.sentry.io/platforms/javascript/enriching-events/context/#passing-context-directly
> 
> ```
> if (!e.response) {
>    e.ramiel_message = `undefined response in error`;
> }
> else if (409 === status) {
>    const userAgent = 'user-agent' in e.response.data ? e.response.data['user-agent'] : '';
> 
>    e.sentry_context = {
>       "Ramiel": {
>           'User Agent': userAgent,
>       }
>    };
>    
>    e.ramiel_message = '사용 중인 장비입니다';
>    if (userAgent) e.ramiel_message += ` (${userAgent})`;
> }
> else if (410 === status) {
>    e.ramiel_message = '장비의 연결이 끊어져 있습니다';
> } else {
>    e.ramiel_message = `[${WebDriverAgentProxy.TAG}] failed to create a session for ${this.udid}`;
> }
> ```
> 
> ```
>                const self = this;
>                Sentry.captureException(e, scope => {
>                    scope.setTags('ramiel_device_type', 'iOS');
>                    scope.setTags('ramiel_device_id', self.udid);
>                    scope.setTags('ramiel_message', e.ramiel_message);
>                    if (e.setry_context) {
>                        scope.setContext("Ramiel", e.sentry_context['Ramiel']);
>                    }
>                    return scope;
>                });
> ```

@yoonjs2 // 해당 형태로 구현 가능하여 진행하였습니다.
추가로, `const self = this;` 구문을 사용하신 이유가 무엇인지 문의드립니다 🙏

2022-11-04 05:57 UTC, yoonjs2 commented
@metocks // this가 udid가 아닌 sentry 객체로 설정될까봐 저렇게 하였습니다. 만일 scope callback 안에서도 this.udid로 udid값을 가져올수 있으면 빼도 될것 같습니다.

2022-11-04 06:02 UTC, metocks commented
> @metocks // this가 udid가 아닌 sentry 객체로 설정될까봐 저렇게 하였습니다. 만일 scope callback 안에서도 this.udid로 udid값을 가져올수 있으면 빼도 될것 같습니다.

@yoonjs2 // sentry에서 노출되는 결과로 볼 때, this는 Sentry 객체가 아닌 것이 확실해 보입니다:
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/12525941/199902456-e5ed60b3-611b-4795-9976-cee107c16aca.png">

따라서 현행 구현을 유지해도 무방해 보입니다 🙏

2022-11-05 08:24 UTC, yoonjs2 commented on src/server/appl-device/mw/WebDriverAgentProxy.ts
> +                const mm = e.text || e.message || '알 수 없는 이유로 장비 초기화에 실패하였습니다.';
@metocks // 본 코멘트 반영여부 결정 부탁드립니다. (빠트리신것 같아 리마인드 드립니다.)

2022-11-06 09:02 UTC, metocks commented on src/server/appl-device/mw/WebDriverAgentProxy.ts
> +                const mm = e.text || e.message || '알 수 없는 이유로 장비 초기화에 실패하였습니다.';
> @metocks // 본 코멘트 반영여부 결정 부탁드립니다. (빠트리신것 같아 리마인드 드립니다.)

@yoonjs2 // 다음 형태로 반영하였습니다. 참고 부탁드립니다:
![image](https://user-images.githubusercontent.com/12525941/200160448-475de135-2343-444c-9777-0be2af2eef3a.png)

2022-11-07 03:32 UTC, yoonjs2 approved these changes

2022-11-07 03:32 UTC, merged