DEV-16317 [라미엘] 초기화 실패 이슈- WDA 죽을 때 동작 이상
HardBoiledSmith/ws-scrcpy pull request #118
Opened 2022-11-08 02:43 UTC by metocks

### What is this PR for?
- 이중 wda.release() 동작 제거
- 초기화 실패에 영향을 미치는 이슈는 아니나, 버그는 맞기에 PR 작성

### How should this be tested?
- ramiel 저장소로 배포: `./provisioning.py on-premise`
- ios 장비 접속
- 브라우저로 장비 접속
- xcodebuild 프로세스 kill: `kill -9 $(ps -ef |grep xcodebuild | grep -v grep | awk '{print $2}')`
- filelock 로그가 뜨지 말아야 함

### Screenshots (if appropriate)

![image-20221108-021752](https://user-images.githubusercontent.com/12525941/200462293-b9867078-7614-4688-a3df-c15f393f84db.png)

2022-11-24 01:43 UTC, singetta requested changes
@metocks // WDA 동작 이상 수정 감사합니다. 아래 리뷰 확인 부탁드립니다.

2022-11-24 01:43 UTC, singetta commented on src/server/mw/MjpegProxyFactory.ts
> +            //
proxy.on 'streamstop' 함수가 실행 가능한게 없다면 `proxy.on('streamstop', ...)` 자체를 삭제해도 되지 않을까요?

2022-11-24 07:30 UTC, yoonjs2 requested changes

2022-11-24 07:30 UTC, yoonjs2 commented on src/server/mw/MjpegProxyFactory.ts
> +            //
@metocks // 저도 아래 2가지 처리를 추가할게 아니라면 빈 핸들러를 (dangling handler) 없애는게 낫지 않을까 합니다.
1) wda가 이미 release 되어 있는지 확인후 release 처리
2) sentry 로그 수집 추가 (wda가 release 안되었는데 스트림이 닫히는 경우 파악)
```
if (!wda.isReleased) {
   wda.release();
} else {
   throw new Exception('mjpeg stream closed before wda released');
}
```

2022-11-24 07:35 UTC, GoldieKMG approved these changes
코드작업 감사합니다  :) 
민수님, 시헌님 주신 코멘트 외 이견 없습니다 🙏

2022-11-25 01:28 UTC, metocks commented on src/server/mw/MjpegProxyFactory.ts
> +            //
@yoonjs2 @singetta // 민수님의 제안대로 진행하도록 하겠습니다.
MjpegProxyFactory에서는 WDA 세션을 건드리지 않도록 의도하였습니다.

2022-11-25 01:45 UTC, singetta approved these changes

2022-11-25 07:07 UTC, yoonjs2 approved these changes

2022-11-25 07:07 UTC, merged