DEV-17245 AES_KEY와 HMAC 키 분리 - DEV-16883, 15945 통합 PR
HardBoiledSmith/ws-scrcpy pull request #131
Opened 2023-01-05 02:31 UTC by metocks

### What is this PR for?
- 테스트를 통합하고, 혼란을 파하기 위해 PR을 합침
- 참조:
    - ㅁ

### How should this be tested?
- OAUTH2.0 테스트 참조: https://github.com/HardBoiledSmith/ws-scrcpy/pull/130/files- HMAC 키 분리 테스트 참조: 
- HMAC KEY 도입 참조: https://github.com/HardBoiledSmith/ws-scrcpy/pull/122

2023-01-12 08:38 UTC, singetta requested changes
@metocks // accessToken을 사용하게끔 추가 되었네요. 코드 추가 감사합니다. 아래 한 건만 확인 부탁드립니다.

2023-01-12 08:38 UTC, singetta commented on src/server/services/HttpServer.ts
> +                        };
들여쓰기가 한 번 더 들어간 듯 한데요. 확인 부탁드립니다.

2023-01-12 13:40 UTC, metocks commented on src/server/services/HttpServer.ts
> +                        };
> 들여쓰기가 한 번 더 들어간 듯 한데요. 확인 부탁드립니다.

@singetta // 반영하였습니다. 리뷰 감사합니다 :)

2023-01-14 12:32 UTC, yoonjs2 approved these changes

2023-01-15 06:36 UTC, GoldieKMG approved these changes
반영 감사합니다 🙏

2023-01-16 04:45 UTC, merged