SA-1283 [라미엘] iOS와 Android 기능 동기화
HardBoiledSmith/ws-scrcpy pull request #141
Opened 2023-04-04 05:15 UTC by ricepower

### What is this PR for?
- 라미엘 Android 앱 종료 기능 추가

### How should this be tested?
- 라미엘 dev 배포: ./provisioning.py dev
- ws-scrcpy 배포: npm run dist:dev && node dist/index.js
- 왼쪽 상단 앱종료 버튼 동작 확인

### Screenshots (if appropriate)
![스크린샷 2023-04-04 오후 2 09 11](https://user-images.githubusercontent.com/6683184/229693399-049ec4c4-d789-41d9-9275-a32532b77791.png)

2023-04-06 01:09 UTC, metocks requested changes
@ricepower // 앱 닫기 기능 구현 감사합니다 👍 
리뷰 1건 검토 부탁드립니다 🙏

2023-04-06 01:09 UTC, metocks commented on src/server/goog-device/mw/WebsocketProxyOverAdb.ts
> +                                return;
```suggestion
```
@ricepower // return은 없어도 무방해 보입니다. 제거를 제안하여 드립니다 🙏

2023-04-06 06:53 UTC, singetta approved these changes
android app terminate 기능 추가 감사합니다. 시헌님 리뷰 확인 부탁드립니다.

2023-04-06 23:12 UTC, GoldieKMG approved these changes
코드 이견 없습니다 시헌님 리뷰 확인해주시면 될 것 같습니다 🙏

2023-04-07 00:21 UTC, ricepower commented on src/server/goog-device/mw/WebsocketProxyOverAdb.ts
> +                                return;
![스크린샷 2023-04-07 오전 9 19 55](https://user-images.githubusercontent.com/6683184/230516097-49f23a2a-0012-46c2-9adb-0b86f71ba0bb.png)

return 값이 반드시 필요하여 넣었습니다. 🙏

2023-04-07 01:03 UTC, metocks approved these changes
확인 감사합니다 👍

2023-04-07 02:32 UTC, merged