(WIP) DEV-18710 [라미엘] 장비 별 팀 할당 멀티 지정 가능
HardBoiledSmith/ws-scrcpy pull request #152
Opened 2023-06-23 13:18 UTC by metocks

### What is this PR for?
- 이 PR이 해결하고자 하는 이슈(JIRA Issue) 및 작업 내용에 대해 설명해 주세요

### How should this be tested?
- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요

### Screenshots (if appropriate)
- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)

2023-06-26 23:12 UTC, singetta approved these changes

2023-06-26 23:27 UTC, singetta requested changes
@metocks // approve 후에 naoko 코드보다가 변경하였는데요. 이렇게 바꾸면 OP환경에서 real device 연결하는 겐도에 영향가지 않을까 의문이 듭니다. (gendo에서는 redirect url에 teamName이 포함되어 있지 않음. naoko에서 녹화한 신규 스크립트만 gendo에서 동작될 것으로 보임)
이 부분 확인 부탁드리며 당분간은 ws-scrcpy쪽에서 기존처럼 teamname을 확인하지 않는게 어떨까 의견 드립니다.

2023-06-27 00:21 UTC, metocks commented
> @metocks // approve 후에 naoko 코드보다가 변경하였는데요. 이렇게 바꾸면 OP환경에서 real device 연결하는 겐도에 영향가지 않을까 의문이 듭니다. (gendo에서는 redirect url에 teamName이 포함되어 있지 않음. naoko에서 녹화한 신규 스크립트만 gendo에서 동작될 것으로 보임)

@singetta // gendo에는 영향이 없습니다. naoko는 access token (IsTeamUser)을 사용하지만, gendo는 HMAC signature (IsSignatureValid)인증을 사용하기 때문입니다.

2023-06-27 00:27 UTC, metocks commented
> > @metocks // approve 후에 naoko 코드보다가 변경하였는데요. 이렇게 바꾸면 OP환경에서 real device 연결하는 겐도에 영향가지 않을까 의문이 듭니다. (gendo에서는 redirect url에 teamName이 포함되어 있지 않음. naoko에서 녹화한 신규 스크립트만 gendo에서 동작될 것으로 보임)
> 
> @singetta // 다음의 이유로, 구현 유지를 제안하여 드립니다:
- gendo에는 영향이 없습니다. naoko는 access token (IsTeamUser)을 사용하지만, gendo는 HMAC signature (IsSignatureValid)인증을 사용하기 때문입니다.
- sachiel에서 원래 객체 하나당 팀 하나의 암묵적인 원칙이 있습니다. 이 원칙을 이용하여 유저가 객체에 접근 관힌이 있는지를 판별합니다. 그러나 이 구현에서 예외적으로  team 컬럼이 3개로 늘어나서, 기존의 원칙대로 접근 권한을 판별할 수 없게 되었습니다. 이로 인한 고육지책으로 team-name query param을 추가하였습니다.

확인 부탁드립니다 🙏

2023-06-27 00:34 UTC, singetta commented
> > > @metocks // approve 후에 naoko 코드보다가 변경하였는데요. 이렇게 바꾸면 OP환경에서 real device 연결하는 겐도에 영향가지 않을까 의문이 듭니다. (gendo에서는 redirect url에 teamName이 포함되어 있지 않음. naoko에서 녹화한 신규 스크립트만 gendo에서 동작될 것으로 보임)
> > 
> > 
> > @singetta // 다음의 이유로, 구현 유지를 제안하여 드립니다:
> 
> * gendo에는 영향이 없습니다. naoko는 access token (IsTeamUser)을 사용하지만, gendo는 HMAC signature (IsSignatureValid)인증을 사용하기 때문입니다.
> * sachiel에서 원래 객체 하나당 팀 하나의 암묵적인 원칙이 있습니다. 이 원칙을 이용하여 �유저가 객체에 접근 관힌이 있는지를 판별합니다. 그러나 이 구현에서 예외적으로  team 컬럼이 3개로 늘어나서, 기존의 원칙대로 접근 권한을 판별할 수 없게 되었습니다. 이로 인한 고육지책으로 team-name query param을 추가하였습니다.
> 
> 확인 부탁드립니다 🙏

@metocks // gendo에서 HMAC인증을 쓰고 있는걸 깜박했네요. 상세 설명 감사합니다. 👍🏼 
ws-scrcpy에서 teamname확인 approve로 변경하였습니다.

2023-06-27 00:34 UTC, singetta approved these changes

2023-06-27 01:57 UTC, yoonjs2 approved these changes
코드에 이견 없습니다. QA 환경에서 통합 점검해 보겠습니다.

2023-06-27 01:57 UTC, merged