DEV-18843 [라미엘] 좌표 클릭 이상 #2 로깅 추적 및 해결방안 모색
HardBoiledSmith/ws-scrcpy pull request #173
Opened 2023-08-04 08:20 UTC by metocks

### What is this PR for?
- 다음 오류메시지 발생 시 클릭이벤트가 제대로 발생하지 않음: `UnknownError: An unknown server-side error occurred while processing the command. Original error: Invalid parameter not satisfying: point.x != INFINITY && point.y != INFINITY`
- ChatGPT에서 다음 케이스를 제시: 아직 UI 요소가 로딩되지 못했거나 애니메이트 중일 때 발생할 수 있음
- 모든 케이스가 초기화 절차 직후 클릭에서 발생하였음. 이에 상당히 높은 연관이 있어 보임
- 따라서, 해당 에러 메시지 발생 시 3회의 재시도 회수를 주기로 하였음

### How should this be tested?
- OP 0137-I-13-Pro 장비의 lfmall 테스트에서 클릭이 먹히는 증상 완화 (주 3~5회로 추정)

2023-08-17 01:05 UTC, singetta approved these changes
재시도 가능 코드 확인하였습니다. 구현에 이견 없습니다. 감사합니다.

2023-08-17 01:24 UTC, GoldieKMG approved these changes
챗 GPT 내용과 연관하여 문제해결 확인했습니다 😃 
해당 에러 발생 시 클릭 재시도 건으로 해결하는 내용 확인했습니다. 반영감사합니다

2023-08-21 02:58 UTC, yoonjs2 approved these changes

2023-08-21 03:02 UTC, yoonjs2 requested changes
@metocks // 조금 이상한게 있어 검토를 요청드립니다.

2023-08-21 03:02 UTC, yoonjs2 commented on src/server/appl-device/services/WDARunner.ts
> +                    this.emit('status-change', { status: WdaStatus.END_ACTION, text: '제어 완료' });
@metocks // 1회 라도 성공하면 루프를 빠져나가야 하지 않을까요?
```suggestion
                    this.emit('status-change', { status: WdaStatus.END_ACTION, text: '제어 완료' });
                    break;
```

2023-08-21 03:02 UTC, yoonjs2 commented on src/server/appl-device/services/WDARunner.ts
> +            this.emit('status-change', { status: WdaStatus.END_ACTION, text: '제어 완료' });
@metocks // 470L 에서도 아래 이 코드를 호출하는데 이러면 2번 메세지가 가는 꼴 아닌가요? 한번만 보내도 되지 않을까요?
```suggestion
```

2023-08-21 04:03 UTC, metocks commented on src/server/appl-device/services/WDARunner.ts
> +            this.emit('status-change', { status: WdaStatus.END_ACTION, text: '제어 완료' });
@yoonjs2 // 확인 고맙습니다. 큰일날 뻔 했네요

2023-08-21 06:31 UTC, yoonjs2 requested changes

2023-08-21 06:31 UTC, yoonjs2 commented on src/server/appl-device/services/WDARunner.ts
> +            this.emit('status-change', { status: WdaStatus.END_ACTION, text: '제어 완료' });
@metocks // break 문 추가를 해도 END_ACTION 메세지는 2번 발송되는데요... 수정 전 로직도 이와 동일한데 의도된 건지 확인 부탁드립니다. 아니라면 496L은 빼는게 좋을것 같습니다.

- 정상: 제어완료(470L) -> 제어완료(496L)
- 예외발생시: 제어실패(486L) -> 제어완료(496L)

2023-08-22 03:45 UTC, metocks commented on src/server/appl-device/services/WDARunner.ts
> +            this.emit('status-change', { status: WdaStatus.END_ACTION, text: '제어 완료' });
> @metocks // break 문 추가를 해도 END_ACTION 메세지는 2번 발송되는데요... 수정 전 로직도 이와 동일한데 의도된 건지 확인 부탁드립니다. 아니라면 496L은 빼는게 좋을것 같습니다.
> 
> * 정상: 제어완료(470L) -> 제어완료(496L)
> * 예외발생시: 제어실패(486L) -> 제어완료(496L)

@yoonjs2 // 중복 메시지를 제거했습니다. 상세한 리뷰 감사합니다.

2023-08-22 04:07 UTC, yoonjs2 approved these changes

2023-08-22 04:07 UTC, merged