DEV-19148 [라미엘] ws-scrcpy 재시작 시 장비 사용 해제기능 정상 작동 확인
HardBoiledSmith/ws-scrcpy pull request #178
Opened 2023-09-01 05:46 UTC by metocks

### What is this PR for?
- sentry/node==7.66.0 사용 시 실행 오류 발생
    - op패치 직후 릴리즈 되었음
- 7.65.0으로 버전 고정

### How should this be tested?
- 라미엘 배포: `$ BRANCH_WS_SCRCPY=DEV-19148 ./provisioning.py on-premise`
- 장비 정상 접속

2023-09-07 01:27 UTC, singetta approved these changes
sentry 버전 고정 및 env path 추가 확인하였습니다.

2023-09-07 05:31 UTC, GoldieKMG approved these changes
수정 감사합니다 이견 없습니다 🙏 QA에서 테스트 해보려면 어떻게 테스트를 진행해야 할까요?  재현 및 테스트를 위해 장비 사용 해제기능이 어느때 사용되는지 설명 요처드려도 될까요?

2023-09-08 06:05 UTC, yoonjs2 requested changes
@metocks // 9/19 전에 OP에 hotfix 해야하는 건일까요?

2023-09-08 06:05 UTC, yoonjs2 commented on src/server/Utils.ts
> +            process.env.PATH += ':/opt/homebrew/bin/';
@metocks // 이곳에 두면 호출할때마다 PATH가 커져서 안될것 같습니다.  차라리 import 문 아래 배치하는게 좋을것 같습니다.

2023-09-08 06:05 UTC, yoonjs2 commented on src/server/Utils.ts
> +            process.env.PATH += ':/opt/homebrew/bin/';
@metocks // 이곳에 두면 호출할때마다 PATH가 커져서 안될것 같습니다.  차라리 import 문 아래 배치하는게 좋을것 같습니다.

2023-09-11 00:13 UTC, metocks commented on src/server/Utils.ts
> +            process.env.PATH += ':/opt/homebrew/bin/';
@yoonjs2 // 반영하였습니다

2023-09-11 00:14 UTC, metocks commented on src/server/Utils.ts
> +            process.env.PATH += ':/opt/homebrew/bin/';
@yoonjs2 // 반영하였습니다

2023-09-11 03:40 UTC, yoonjs2 approved these changes

2023-09-11 03:40 UTC, merged