DEV-19351 [라미엘] 안드로이드 sendtext 문제해결시도 #2
HardBoiledSmith/ws-scrcpy pull request #199
Opened 2024-01-22 06:09 UTC by metocks

### What is this PR for?

- adb keyboard를 이용한 범용적인 sendText 구현
- 침조
    - https://github.com/HardBoiledSmith/ramiel/pull/481
    - 

### How should this be tested?

- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요

### Screenshots (if appropriate)

- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)

2024-01-26 06:19 UTC, singetta requested changes
@metocks // adbkeyboard기반 sendtext 기능 구현 코드 확인하였습니다. 아래 리뷰 확인 부탁드려요.

2024-01-26 06:19 UTC, singetta commented on src/server/goog-device/mw/WebsocketProxyOverAdb.ts
> +                        * */
해당 주석은 구현 시 사용했던 케이스로 이제 삭제해도 되지 않을까요?

2024-01-26 06:33 UTC, metocks commented
> @metocks // adbkeyboard기반 sendtext 기능 구현 코드 확인하였습니다. 아래 리뷰 확인 부탁드려요.

@singetta // 리뷰 반영하였습니다. 감사합니다 👍

2024-01-26 06:35 UTC, singetta approved these changes

2024-01-26 06:42 UTC, yoonjs2 approved these changes
@metocks // 수정 감사합니다. 코드상 배포시 모든 안드로이드 장비에 일괄 반영될것 같은데요... 운영팀에 sendtext 쓰는 패턴이 어떨지 몰라서 배포후 좀 이슈가 있을것 같습니다. 운영팀에 미리 공유해 두는게 필요할것 같네요.

2024-01-28 20:27 UTC, GoldieKMG approved these changes
코드 이견 없습니다 수정 감사합니다 🙏

2024-01-29 08:53 UTC, yoonjs2 commented
> @metocks // 수정 감사합니다. 코드상 배포시 모든 안드로이드 장비에 일괄 반영될것 같은데요... 운영팀에 sendtext 쓰는 패턴이 어떨지 몰라서 배포후 좀 이슈가 있을것 같습니다. 운영팀에 미리 공유해 두는게 필요할것 같네요.

@metocks // 아래 2 장비 적용상황에 따라 어떻게 되는지 확인이 필요할것 같습니다.
- 0043-G-S21
- 0081-G-Note20U
https://hbsmith.slack.com/archives/C289806JG/p1706509944581229

2024-01-30 01:50 UTC, merged