DEV-21037 [데이터팀: 개발팀] 라미엘 스크롤 이동이 종료되지 않은 상태에서 다음 스텝의 (탐지후)클릭이 동작하는 현상 수정 요청
HardBoiledSmith/ws-scrcpy pull request #218
Opened 2024-08-13 01:35 UTC by metocks

### What is this PR for?
- 이 PR이 해결하고자 하는 이슈(JIRA Issue) 및 작업 내용에 대해 설명해 주세요

### How should this be tested?
- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요

### Screenshots (if appropriate)
- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)

2024-08-22 05:08 UTC, singetta requested changes
@metocks // 라미엘 v1에서 isReadyToUse, isScrolling 구현 코드 확인하였습니다. [ramiel 리뷰](https://github.com/HardBoiledSmith/ramiel/pull/586#pullrequestreview-2253311972)에서 말씀드린 것처럼 setTimeout만으로는 스크롤 완료 상태를 확인하기는 어려워보입니다.

2024-08-22 05:08 UTC, singetta commented on src/app/applDevice/toolbox/QVHackToolBox2.ts
> +                            }, 4000);
4초 이후에도 계속 스크롤링 상태에 있어 보입니다.

2024-08-22 05:08 UTC, singetta commented on src/app/googDevice/toolbox/DroidToolBox2.ts
> +                        }, 3000);
3초 이후에도 계속 스크롤링 상태에 있어 보입니다.

2024-08-22 05:08 UTC, singetta commented on src/app/googDevice/toolbox/DroidToolBox2.ts
> +                        }, 3000);
3초 이후에도 계속 스크롤링 상태에 있어 보입니다.

2024-08-23 05:42 UTC, metocks commented
@singetta // 아이폰 한정 스크롤링 상태를 정확하게 감지하도록 수정하였습니다

https://github.com/user-attachments/assets/a4b481cb-145d-4092-a72a-dcc08ad6e71a

안드로이드는 adb 구조 상 구현이 어려울 것 같습니다.

2024-08-26 01:07 UTC, singetta approved these changes
안드로이드의 경우 실행 결과를 확인할 수 없어서 아쉽네요. 현재 구현하신 방법이 최선인 듯 하여 approve하도록 하겠습니다. 수정 감사합니다.

2024-08-27 02:44 UTC, yoonjs2 approved these changes

2024-08-27 02:56 UTC, merged