DEV-14464 [라미엘] user-agent 버그 수정: 세션을 점유한 실제 user-agent 노출
HardBoiledSmith/ws-scrcpy pull request #52
Opened 2022-03-30 10:40 UTC by metocks

### What is this PR for?

- 세션을 점유한 실제 user-agent 노출
- 참조
    - https://github.com/HardBoiledSmith/ws-scrcpy/pull/52
    - https://github.com/HardBoiledSmith/hbsmith-database/pull/322
    - https://github.com/HardBoiledSmith/sachiel/pull/1066

### How should this be tested?

- 의존성 배포:
    - db: master vagrant up
    - sachiel: DEV-14464 vagrant up
- ramiel 서비스 배포:
    - master 브렌치 복제
    - 배포: `./terminate.py; BRANCH_WS_SCRCPY=DEV-14464 ./provisioning.py on-premise`
- android 1, iOS 1기씩 연결
- 크롬 브러우저 열기
- 안드로이드 테스트: 2번째 세선에서 사용 중 뜨는지 확인
    - 세션 A: http://localhost:28500/?app_key=com.lotte&user-agent=SESSION__A__#!action=stream&player=mse&udid=28e0e16c28057ece&ws=ws%3A%2F%2Flocalhost%3A28500%2F%3Faction%3Dproxy-adb%26remote%3Dtcp%253A8886%26udid%3D28e0e16c28057ece
    - 세션 B: http://localhost:28500/?app_key=com.lotte&user-agent=SESSION__B__#!action=stream&player=mse&udid=28e0e16c28057ece&ws=ws%3A%2F%2Flocalhost%3A28500%2F%3Faction%3Dproxy-adb%26remote%3Dtcp%253A8886%26udid%3D28e0e16c28057ece
- iOS 테스트:
    - 세션 A:http://localhost:28500/?app_key=com.lotte.smartwish&user-agent=SESSION__A__#!action=stream-mjpeg&player=mjpeghttp&udid=00008020-00094C693A33002E
    - 세션 B:http://localhost:28500/?app_key=com.lotte.smartwish&user-agent=SESSION__B__#!action=stream-mjpeg&player=mjpeghttp&udid=00008020-00094C693A33002E

### Screenshots (if appropriate)

- 영상 첨부

https://user-images.githubusercontent.com/12525941/160815844-93dee8bc-f4c2-44be-97a6-e918e2b9564e.mov

2022-04-07 05:02 UTC, singetta requested changes
@metocks // error 처리에 user-agent 정보를 반영하도록 하였군요. 수정 감사합니다. 아래 리뷰 내용 확인 부탁드립니다.

2022-04-07 06:30 UTC, yoonjs2 approved these changes
@metocks // @singetta 님 의견대로 merge가 제대로 안된 부분이 있는것 같습니다. 확인 부탁드리겠습니다.

2022-04-07 06:30 UTC, yoonjs2 requested changes
@metocks // @singetta 님 의견대로 merge가 제대로 안된 부분이 있는것 같습니다. 확인 부탁드리겠습니다.

2022-04-08 04:23 UTC, GoldieKMG approved these changes
추가 고맙습니다. 코드 이견 없습니다 아래 민수님 의견 반영되면 될 것 같습니다

2022-04-08 05:13 UTC, metocks commented on src/server/goog-device/mw/WebsocketProxyOverAdb.ts
> +>>>>>>> d12b76c41446c3888721a5304e2b2944c175d158
> merge가 제대로 안된 것 같습니다.

확인 고맙습니다 🙏

2022-04-08 06:25 UTC, yoonjs2 approved these changes

2022-04-08 06:25 UTC, merged