(WIP) DEV-15202 [라미엘] iOS 클릭먹통과 10분 이상 대기 시 terminateApp 1분 멈춤 이슈
HardBoiledSmith/ws-scrcpy pull request #79
Opened 2022-06-02 06:50 UTC by metocks

### What is this PR for?

- 이슈 상세: https://hbsmith.atlassian.net/wiki/spaces/GEN/pages/2368929913/Ramiel#2022-5-30-iOS-%ED%81%B4%EB%A6%AD%EB%A8%B9%ED%86%B5%EA%B3%BC-%ED%94%84%EB%A6%AC%EC%A7%95-%EC%9D%B4%EC%8A%88
- wdaEvent Queue 관련 초기화 버그 수정
- ㄴ
- 제어 명령 수행 시 상태 메시지를 보여주고 마우스 아이콘을 WAIT로 변경

### How should this be tested?

- 선택적으로 수행: 프로비저닝 프로필에 등록된 iOS 장비가 있는 경우에만 가능
- sachiel, db master vagrant up
- ramiel 배포:
    ```bash
    export BRANCH=DEV-15202
    export BRANCH_WS_SCRCPY=DEV-15202
    ./provisioning.py on-premise
```
- 10분 텀을 두고 시작 시, 1분 타임아웃이 발생하지 않는지 확인
    -수동으로 iOS 조작:
    - 롯데온 앱 실행
    - 장비 잠금
    - 11분 대기 (최소 10분. 넉넉히 1분 더)
    - 브라우저를 열고 해당 장비로 세션 접속
    - 롯데온 앱 자동 시적 설정
    - 예) `http://localhost:28500/?app_key=com.lotte.smartwish&user-agent=HELLO_WORL22222222D#!action=stream-mjpeg&player=mjpeghttp&udid=00008020-00094C693A33002E`
    - 타임아웃 없이 앱 시작까지 10초 이상의 딜레이 없이 수행 완료
- 제어 명령 후 상태 메시지와 아이콘 상대 확인

### Screenshots (if appropriate)

- 타임아웃 이슈 해결
https://user-images.githubusercontent.com/12525941/171570213-c57f90d6-c421-4945-9eab-5a5890eeaa77.mov

- 제어 명령 후 UI 변화 확인
https://user-images.githubusercontent.com/12525941/171570247-f35fc274-7e17-41ba-b385-e5028c5c0f78.mov

2022-06-09 00:14 UTC, singetta requested changes
@metocks // 코드 확인 하였습니다. 로그 내용이 많아졌네요. 이슈 발생 시 gendo CDT log로 상황 분석이 가능하겠네요. PR명에 `(WIP)`가 붙어있는데요. 아직 작업 중이신 걸까요? 연관 이슈는 `(WIP)`가 없어서 해당 PR도 리뷰 하였는데요. PR명 확인 부탁드립니다.

2022-06-09 00:59 UTC, metocks commented
> @metocks // 코드 확인 하였습니다. 로그 내용이 많아졌네요. 이슈 발생 시 gendo CDT log로 상황 분석이 가능하겠네요. PR명에 `(WIP)`가 붙어있는데요. 아직 작업 중이신 걸까요? 연관 이슈는 `(WIP)`가 없어서 해당 PR도 리뷰 하였는데요. PR명 확인 부탁드립니다.

@singetta // 확인 고맙습니다. 접두어를 제거하였습니다 :)

2022-06-09 01:39 UTC, singetta approved these changes

2022-06-09 05:55 UTC, GoldieKMG approved these changes
ios 건이라 개발환경에서 직접 테스트는 어려울 것 같습니다. 해당 내용 확인했습니다 :) 
코드 이견 없습니다. 로깅들이 많이 추가되었네요 🙏

2022-06-09 06:43 UTC, yoonjs2 reviewed
@metocks // 시헌님 `세션 시작 시, 앱 키로 종료하는 기능 폐지` 로 인해서 다음 케이스가 우려되는데요 실제로 발생할수 있는 사항인지 확인 한번 부탁드리겠습니다.

1) 이전 세션에서 명시적으로 앱 종료 안하고 세션을 나간 경우, 새 세션에서 이전 세션의 앱이 열려 있어 테스트에 영향 받음 (3R 실패)

그리고 앱키로 앱 실행시 앱이 초반에 잠깐 깜빡이더라도 앱 실행 -> 종료 -> 재실행 식으로 동작하도록 작업 하실거라고 이야기 하셨던 기억이 있는데 이부분에 문제가 생기서 `세션 시작 시, 앱 키로 종료하는 기능 폐지` 로 작업하신건지 궁금합니다.

2022-06-10 01:15 UTC, metocks commented
> ios 건이라 개발환경에서 직접 테스트는 어려울 것 같습니다. �해당 내용 확인했습니다 :) 코드 이견 없습니다. 로깅들이 많이 추가되었네요 🙏

@yoonjs2 // PR에 회의에서 논의한 내용을 수정하지 않았습니다.
다음대로 적용한 것이 맞습니다: *앱키로 앱 실행시 앱이 초반에 잠깐 깜빡이더라도 앱 실행 -> 종료 -> 재실행 식으로 동작하도록 작업*

2022-06-10 06:34 UTC, merged